### ISSUE TITLE
Sitemap for workers has bad urls

### ISSUE THREAD

**Issue by dknecht** [cloudflare/cloudflare-docs-engine#289]
https://developers.cloudflare.com/workers/sitemap.xml

Example is "http://developers.cloudflare.com/workers/workers/learning/using-durable-objects" It has two "workers"

**Comment by signalnerve** [comment]
@adamschwartz i think we'll need to override the `gatsby-plugin-sitemap` config, as seen [here](https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/)

**Comment by adamschwartz** [comment]
Can we use `resolveSiteUrl` (from your link)?

**Comment by dknecht** [comment]
Why does it only happen for some urls?
