### ISSUE TITLE
Firefox styling bug on navigation buttons

### ISSUE THREAD

**Issue by renandincer** [cloudflare/cloudflare-docs-engine#305]
Example:
<img width="155" alt="Screen Shot 2020-11-13 at 12 31 41 PM" src="https://user-images.githubusercontent.com/1429100/99121759-d8b34b00-25b1-11eb-9a02-66fcabf4807f.png">

**Comment by adamschwartz** [comment]
Fixed with https://github.com/cloudflare/cloudflare-brand-assets/commit/4847bcfaca075eac0ed22c633f3f5e329d9367a6
