### ISSUE TITLE
Copy Workers content from this repo to new Cloudflare docs content repo

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/cloudflare-docs-engine#66]
New location: https://github.com/cloudflare/cloudflare-docs (inside `products/workers` folder).

- [x] Move `docs-config.js`
- [x] Move `src/content` to `products/workers/src/content`
- [x] Transfer over [Github issues on this repo with `label: content`](https://github.com/cloudflare/workers-docs-engine/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Acontent)

**Comment by nandanv2702** [comment]
Hey! I'd like to contribute to this task. Could you please provide more information on what needs to be done here?

**Comment by adamschwartz** [comment]
Hey @nandanv2702 thanks so much for offering. We’re still evaluating which way we want to go about doing this. We’ll keep you posted.

**Comment by nandanv2702** [comment]
Alright, thank you so much! I'd love to contribute to any other issues you have open, so please let me know if there's anything I can do!
