### ISSUE TITLE
Support external links in the sidebar nav

### ISSUE THREAD

**Issue by davidtsong** [cloudflare/cloudflare-docs-engine#94]
I'm trying to add a link to the REST API in the navbar. With the current design, it'd go in the hamburger - three dot menu as shown in the screenshot below

![image](https://user-images.githubusercontent.com/7200438/88965389-8e56ca00-d25f-11ea-8430-4c58a0bf49a6.png)

I'm worried these links might be too hidden away for people to see. Could we have these external links in the navbar with some kind of divider to make the distinction? (Could probably include a small h3/4 title too if needed)

![Screen Shot 2020-07-30 at 12 24 11 PM](https://user-images.githubusercontent.com/7200438/88965474-aaf30200-d25f-11ea-9e0e-ac50712eeb65.png)

**Comment by adamschwartz** [comment]
Thanks for bring this up.

An early mock we had did support external links in the sidebar nav:

![image](https://user-images.githubusercontent.com/154613/88966107-ccf97e00-d279-11ea-8b0d-4d935b73bb57.png)

I can see good arguments on both sides. Overall I’d say it may depend on the importance of the external link, and whether or not we feel like it needs to visibly persist.

For example, for the REST API link it may be sufficient to put it in the dropdown and also put it somewhere in the body of the docs homepage.

But for the Playground link, there may be a stronger case to be made that it should be more persistent. That being said, something like that could be featured in the Examples overview page, and individual Example pages should essentially be embedded playground iframes anyhow.

My short answer is: I think we should explore this design, but I’m not sure for what content. And I do think that the dropdown for external links serves a valuable purpose as well (e.g. for linking to the Workers marketing home page), so I’d want to think carefully about why a link would go in one versus the other.

Thanks again for reminding me about this!

**Comment by davidtsong** [comment]
Cool, I am a fan of having everything on the sidebar. We can have the dropdown somewhere to hide it when we get to many external links (idt we need to optimize early for this). I just think the three dots hides it away such that most users will never find / see those links.

**Comment by davidtsong** [comment]
But mostly, I just want to take "Add restAPI link" off of my todo list so would be great to figure it out soon :)

**Comment by adamschwartz** [comment]
Closing this for now. We haven’t seem to have a need for this during the migration to https://github.com/cloudflare/cloudflare-docs. Can always re-open if this comes up again.
